query GetDetallePedidos($id_pedido:Int){
  GetDetallePedidos(id_pedido:$id_pedido) {
    id
    nombre
    cantidad
    precio
    total
    pedido_id
    producto_id
    data {
      id
      nombre
      slug
      descripcionCorta
      descripcionLarga
      precio_real
      precio_descuento
      stok_minimo
      stok_real
      foto_real{
        id
        url
      }
      open_graph{
        id
        url
      }
      keywords
      favoritos
      estado
      created_at
      updated_at
    }
  } 
}